azimuth_authentication_type: oidc
ingress_tls_enabled: true
azimuth_capi_operator_chart_version: 0.8.7-dev.0.oidc-flavours-test.19
azimuth_identity_operator_chart_version: 0.8.6-dev.0.feat-additional-crds.6

azimuth_capi_operator_capi_helm_chart_name: openstack-cluster
azimuth_capi_operator_capi_helm_chart_repo: https://azimuth-cloud.github.io/capi-helm-charts
azimuth_capi_operator_capi_helm_chart_version: 0.14.2-dev.0.intel-helm.11
azimuth_capi_operator_release_overrides:
  config:
    identity:
      oidcEnabled: true
      defaultUserNamespaceRole:
        namespaces:
        - prod
        - dev
        - staging
      defaultUserClusterRole:
        rules:
        - apiGroups:
          - argoproj.io
          resources:
          - cronworkflows
          - cronworkflows/finalizers
          - clusterworkflowtemplates
          - clusterworkflowtemplates/finalizers
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get","list","watch","create"]

azimuth_capi_operator_cluster_templates_extra:
  intel-gpu-baremetal-dev:
    annotations:
      acl.azimuth.stackhpc.com/allow-list: ''
      acl.azimuth.stackhpc.com/allow-regex: ''
      acl.azimuth.stackhpc.com/deny-list: ''
      acl.azimuth.stackhpc.com/deny-regex: ''
    spec:
      label: intel-gpu-baremetal-dev
      description: HA Kubernetes v1.31.4 with OIDC and Intel XPU plugin
      values:
        kubernetesVersion: v1.31.5
        machineImageId: b323d07a-2f9e-449a-b986-8d2f3e91d4a2

        controlPlane:
          kubeadmConfigSpec:
            clusterConfiguration:
              apiServer:
                extraArgs:
                  enable-admission-plugins: ExtendedResourceToleration

        addons:
          nvidiaGPUOperator:
            enabled: false
          restrictedAdmission:
            enabled: true
            chart:
              repo: https://azimuth-cloud.github.io/restricted-pss-vaps-helm/
            release:
              values:
                defaultBindingNamespaceSelector:
                  matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: In
                    values:
                    - prod
                    - dev
                    - staging
                allowedCapabilities:
                - NET_BIND_SERVICE
                - IPC_LOCK
          intelDevicePlugin:
            enabled: true
            gpuPlugin:
              release:
                values:
                  tolerations:
                  - key: gpu.intel.com/i915
                    operator: "Exists"
                    effect: "NoSchedule"
          monitoring:
            enabled: true
          custom:
            oidc-user-prod-namespace:
              kind: Manifests
              spec:
                namespace: prod
                manifests:
                  prod-namespace.yaml: |
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: prod
            oidc-user-dev-namespace:
              kind: Manifests
              spec:
                namespace: dev
                manifests:
                  dev-namespace.yaml: |
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: dev
            oidc-user-staging-namespace:
              kind: Manifests
              spec:
                namespace: staging
                manifests:
                  staging-namespace.yaml: |
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: staging