flux_enabled: true

azimuth_capi_operator_release_overrides:
  config:
    capiHelm:
      flavorSpecificNodeGroupOverrides:
        '*.pvc.*': #TODO: this assumes your PVC flavours contain '.pvc.' in their name
          kubeadmConfigSpec:
            preKubeadmCommands:
              - |
                # Adapted from https://dgpu-docs.intel.com/driver/installation.html#ubuntu
                sudo apt update
                sudo apt install -y gpg-agent wget
                . /etc/os-release
                if [[ ! " jammy " =~ " ${VERSION_CODENAME} " ]]; then
                    echo "Ubuntu version ${VERSION_CODENAME} not supported"
                else
                    wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | \
                    sudo gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg
                    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu ${VERSION_CODENAME}/lts/2350 unified" | \
                    sudo tee /etc/apt/sources.list.d/intel-gpu-${VERSION_CODENAME}.list
                    sudo apt update
                fi
                sudo apt install -y \
                    linux-headers-$(uname -r) \
                    linux-modules-extra-$(uname -r) \
                    flex bison \
                    intel-fw-gpu intel-i915-dkms xpu-smi
                # Avoids reboot
                modprobe i915
            files:
            - path: /etc/kubernetes/patches/kubeletconfiguration0+strategic.json
              owner: "root:root"
              permissions: "0644"
              content: |
                {
                  "apiVersion": "kubelet.config.k8s.io/v1beta1",
                  "kind": "KubeletConfiguration",
                  "reservedSystemCPUs": "0-3",
                  "cpuManagerPolicy": "static",
                  "cpuManagerPolicyOptions":
                  {
                      "full-pcpus-only": "true",
                  },
                  "topologyManagerPolicy": "restricted",
                  "memoryManagerPolicy": "Static",
                  "reservedMemory": [
                      {
                        "numaNode": 0,
                        "limits": {
                          "memory": "1Gi",
                        }
                      }
                    ],
                  "evictionHard": {
                    "memory.available": "1Gi",
                  },
                }
            joinConfiguration:
              patches:
                directory: /etc/kubernetes/patches
              nodeRegistration:
                taints:
                - effect: NoSchedule
                  key: gpu.intel.com/i915
                
pvc_config_spec:
  values:
    controlPlane:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              enable-admission-plugins: ExtendedResourceToleration
            
    addons:
      cni:
        type: cilium
        cilium:
          release:
            values:
              hubble:
                relay:
                  enabled: true
                ui:
                  enabled: true
      openstack:
        enabled: true
        csiCinder:
          enabled: true
        csiManila:
          enabled: true
          defaultStorageClass:
            isClusterDefault: false
            parameters:
              type: ceph01_cephfs
      monitoring:
        enabled: true
      nodeFeatureDiscovery:
        enabled: true
      intelDevicePlugin:
        enabled: true

azimuth_capi_operator_cluster_templates_default: |-
  {
    {% for key, image in community_images.items() %}
    {% if "kubernetes_version" in image %}
    {% set kube_vn_no_prefix = image.kubernetes_version | regex_replace('^v', '') %}
    {% set kube_vn_dash = kube_vn_no_prefix | replace('.', '-') %}
    "kube-{{ kube_vn_dash }}": {
      "annotations": {{ azimuth_capi_operator_cluster_template_annotations }},
      "spec": {{
        azimuth_capi_operator_cluster_template_defaults |
          combine(
            {
              "label": image.kubernetes_version,
              "description": "Kubernetes " ~ kube_vn_no_prefix ~ " with HA control plane.",
              "values": {
                "kubernetesVersion": kube_vn_no_prefix,
                "machineImageId": community_images_image_ids[key],
              },
            },
            recursive = True
          ) |
          combine(pvc_config_spec, recursive = True)
      }},
    },
    {% endif %}
    {% endfor %}
  }

azimuth_capi_operator_app_templates_extra:
  # The spec for the Intel XPU enabled JupyterHub app template
  jupyterhub-intel:
    annotations:
      acl.azimuth.stackhpc.com/allow-list: ''
      acl.azimuth.stackhpc.com/allow-regex: ''
      acl.azimuth.stackhpc.com/deny-list: ''
      acl.azimuth.stackhpc.com/deny-regex: ''
    spec:
      chart:
        repo: "https://azimuth-cloud.github.io/azimuth-charts"
        name: "jupyterhub-azimuth"
      versionRange: ">=0.0.0"
      keepVersions: 3
      syncFrequency: 86400
      defaultValues:
        jupyterhub:
          singleuser:
            profileList:
              - display_name: "CPU"
                description: "Standard"
              - display_name: "Pytorch environment with 1 x Intel XPUs"
                description: "Intel XPU support"
                kubespawner_override:
                  image: ghcr.io/johngarbutt/jupyterhub-intel-gpu:6421ba1
                  extra_resource_limits:
                    "gpu.intel.com/i915": "1"
                  supplemental_gids:
                    - "110"
                default: true
      label: "JupyterHub (XPU)"
      description: "Multi-user Jupyter notebook environment with Intel GPU support."
  huggingface-intel:
    annotations:
      acl.azimuth.stackhpc.com/allow-list: ''
      acl.azimuth.stackhpc.com/allow-regex: ''
      acl.azimuth.stackhpc.com/deny-list: ''
      acl.azimuth.stackhpc.com/deny-regex: ''
    spec:
      chart:
        repo: https://stackhpc.github.io/azimuth-llm
        name: azimuth-llm-chat
      versionRange: ">=0.0.0"
      keepVersions: 3
      syncFrequency: 86400
      defaultValues:
        azimuth-llm:
          api:
            intelXPUsEnabled: true
      label: "HuggingFace LLM (XPU)"
      description: A generative AI chatbot service backed by a HuggingFace large language model (requires an XPU node group on the target cluster).
